### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by jpison** [busarobi/XMLC#25]
Dear @Robert

I am trying to use my database but I am getting this error:

"
java -Xmx64G -jar XMLC_PLT-jar-with-dependencies.jar -train ./examples/images_trainig

(2017-10-12 13:32:04,324) INFO  [main] [Run.main:21] - --> Use case: -train
(2017-10-12 13:32:04,326) INFO  [main] [Run.main:22] - --> Config file./examples/images_traineval.config
(2017-10-12 13:32:04,329) INFO  [main] [ReadProperty.readProperty:14] - Reading property file...
(2017-10-12 13:32:04,348) INFO  [main] [ReadProperty.readProperty:27] - Done.
(2017-10-12 13:32:04,352) INFO  [main] [AbstractLearner.learnerFactory:72] - --> Learner: PLT
#####################################################
#### Learner: PLT
(2017-10-12 13:32:04,357) INFO  [main] [PLT.<init>:82] - #### gamma: 0.1
(2017-10-12 13:32:04,358) INFO  [main] [PLT.<init>:86] - #### lambda: 1.0E-6
(2017-10-12 13:32:04,358) INFO  [main] [PLT.<init>:90] - #### epochs: 10
(2017-10-12 13:32:04,358) INFO  [main] [PLT.<init>:94] - #### Hasher: Mask
(2017-10-12 13:32:04,359) INFO  [main] [PLT.<init>:98] - #### Number of ML hashed features: 65536
(2017-10-12 13:32:04,359) INFO  [main] [PLT.<init>:103] - #### k (order of the tree): 32
(2017-10-12 13:32:04,359) INFO  [main] [PLT.<init>:107] - #### tree type HuffmanTree
(2017-10-12 13:32:04,359) INFO  [main] [PLT.<init>:111] - #### tree file name ./examples/huffman_tree.txt
#####################################################
(2017-10-12 13:32:04,385) INFO  [main] [HuffmanTree.allocateFrequencies:57] - Building Huffman tree...
(2017-10-12 13:32:07,524) INFO  [main] [HuffmanTree.allocateFrequencies:67] - Huffman tree is built based on 4109 instance.
(2017-10-12 13:32:07,622) INFO  [main] [PLT.allocateClassifiers:152] - #### Num. of labels: 5244 Dim: 2048
(2017-10-12 13:32:07,623) INFO  [main] [PLT.allocateClassifiers:153] - #### Num. of inner node of the trees: 10487
(2017-10-12 13:32:07,623) INFO  [main] [PLT.allocateClassifiers:154] - #####################################################
(2017-10-12 13:32:07,625) INFO  [main] [MaskHasher.<init>:23] - #####################################################
(2017-10-12 13:32:07,626) INFO  [main] [MaskHasher.<init>:24] - #### Mask hash
(2017-10-12 13:32:07,626) INFO  [main] [MaskHasher.<init>:25] - #### Num. of hashed features: 687276032
(2017-10-12 13:32:07,626) INFO  [main] [MaskHasher.<init>:26] - #####################################################
(2017-10-12 13:32:07,626) INFO  [main] [PLT.allocateClassifiers:158] - Allocate the learners...
(2017-10-12 13:32:07,628) INFO  [main] [PLT.train:179] - #############--> BEGIN of Epoch: 1 (10)
**Exception in thread "main" java.lang.NullPointerException
        at util.PrecomputedTree.getTreeIndex(PrecomputedTree.java:163)
        at Learner.PLT.train(PLT.java:192)
        at run.LearnerManager.train(LearnerManager.java:113)
        at run.Run.main(Run.java:27)**

____________________________________________________

- I am using the XMLC package in UBUNTU server with 128G RAM.
- RCV1 example works fine.
- My database is not really sparse (few 0s), only a label per instance:

__________________________
1399978 2048 5244
3215 0:1.547 1:0.334 2:4.682 3:0.833 4:1.276 5:2.471 6:0.093 7:6.782 8:1.244 9:4.614 11:0.337 12:2.486 13:3.119 14:1.342 15:9.064 16:7.158 17:2.437 19:11.947 20:3.874 21:3.484 22:0.771 23:0.252 24:0.75 25:0.117 26:0.338 27:0.481 28:0.046 29:1.157 30:3.128 31:4.092 32:12.482 33:2.001 35:0.557 36:0.689 37:1.899 38:1.839 39:0.531 40:6.176 41:0.552 42:0.3 43:3.966 44:0.05 45:0.304 46:0.083 47:2.576 48:0.982 49:2.126 50:3.599 51:2.458 52:11.496 53:0.381 54:0.332 55:0.543 56:7.134 57:1.741 58:0.107 59:6.345 60:9.532 61:0.318 62:2.448 63:1 64:0.32 65:0.267 66:0.345 67:0.812 68:8.814 69:6.167 70:0.283 .....
_______________

- My java version:

java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

- My config file:

----------------------------------------
IsHeader = true

TrainFile = ./data/train.txt
TestFile = ./data/val.txt

ModelFile = ./examples/deepplt_model_ontrain_images.model

hasher = Mask
MLFeatureHashing = 268435456
Learner = PLT

gamma = 0.1
epochs = 10
lambda = 0.000001
k = 32

treeFile = ./examples/huffman_tree.txt
treeType = HuffmanTree

-------------------------------------------------------

What I am doing wrong?

Thanks in advanced!

**Comment by busarobi** [comment]
Hi Javier,

Thank you for using our package and providing us feedback!

I suspect that problem  should be that the labels are indexed starting from 0 and similarly the features are also indexed from 0. As far as I remember both should be indexed starting from 1. As far as I remember, this is the standard in XMLC repository.

Let me know whether this helps!

Best,R.

**Comment by jpison** [comment]
Hi Robert

But in rcv1x_train.txt I saw features with index 0 ...

____________

> more rcv1x_train.txt | grep ' 0:'

2187 **0:0.140330** 556:0.083430 700:0.072380 1267:0.092870 2552:0.105660 2935:0.039530 3239:0.029990 3436:0.119220 3856:0.067410 3892:0.093340 4261:0.079900 4940:0.105660 5147:0.090330 5451:0.077230 5991:0.058630 6142:0.077850 6625:0.067710 7068:0.070410 7151:0.059370 8066:0.066050 8521:0.047330 8764:0.045150 9241:0.045500 9313:0.117870 9452:0.071580 9953:0.102540 10035:0.103510 10181:0.047000 10255:0.053440 10382:0.063060 10655:0.102540 11505:0.080650 11996:0.164570 12110:0.294500 12122:0.022390 12270:0.055980 12273:0.111310 12357:0.046970 12893:0.095060 13283:0.221620 13819:0.044570 13860:0.033170 14886:0.040950 14969:0.100000 15473:0.140330 15506:0.053720 15640:0.102540 16156:0.097200 17271:0.030430 17346:0.078170 17347:0.089210 17362:0.043590 17922:0.045360 18272:0.040960 18586:0.063230 19231:0.140330 19544:0.055020 19783:0.128560 20694:0.082740 20977:0.045910 20981:0.072840 

258,286,354 **0:0.359980** 522:0.117250 1603:0.097490 2151:0.116210 8674:0.132270 8852:0.131240 9105:0.076450 9191:0.201460 10799:0.085930 12763:0.116250 12820:0.050520

________________________

And my labels are indexed from 1 to 5244..

Thanks

Javier

**Comment by jpison** [comment]
Hi again

I am cheking other databases and the matlab/cpp conversion code from "http://manikvarma.org/downloads/XC/XMLRepository.html" and I see in "Bibtex" dataset that labels and features start from 0.

I am going to try it changing my labels from 0 to 5244-1

Thanks for your advice...

Javier

**Comment by jpison** [comment]
Hi Robert,

I have changed labels from 0 to (5244-1) but after 30min the error appears again...

--------

Exception in thread "main" java.lang.NullPointerException
        at util.PrecomputedTree.getTreeIndex(PrecomputedTree.java:163)
        at Learner.PLT.train(PLT.java:192)
        at run.LearnerManager.train(LearnerManager.java:113)
        at run.Run.main(Run.java:27)

---

Regards

Javier

**Comment by busarobi** [comment]
Hi Javier,

are you available for a short hangout meeting next week? It might be more
efficient if we figure out one to one what went wrong. There might be
something wrong with the code.

Best,
R.

**Comment by jpison** [comment]
Perfect! Thanks for helping me!

My email:    fjmartin@unirioja.es

Best regards
Javi
